### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by Lance117** [LanceSanity/Quarrel#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by evhumphrey** [comment]
Awesome, looks good!

Here's some feedback:

- [ ] Errors should clear after you navigate away. Right now, you can go to 'Sign Up', hit the button and some errors will appear; when navigating to 'Sign In', the errors are still there
- [ ] When logged in, there should be some styling for the logout button
- [ ] I'd have a basic homepage styled as well (it looks a little empty at `/`)
